### ISSUE TITLE
Running instructions

### ISSUE THREAD

**Issue by flochtililoch** [ClementLeBihan/BafangConfigTool_macos#1]
Hi Clement,

I'm trying to run your program and so far have faced the following issues:
- when running with my default user, the program starts correctly, but trying to connect to the serial port yields an error: 
   ```
   Serial port /dev/cu.usbserial-1420 failed to open. You might need root permissions.
   ```

- when I edit the scheme and set "Debug Process As: root", the program crashes as it starts, with the following stack trace:
   <img width="1139" alt="Screen Shot 2020-07-20 at 6 35 43 PM" src="https://user-images.githubusercontent.com/309515/88002756-20b8da00-cab8-11ea-9b58-28a569e505c6.png">

Any clue on how to getting it running would be appreciated!

**Comment by ClementLeBihan** [comment]
Hi Florent,

I'm glad you tried the program.

Right now the serial port number is hard written in the code, i'll add the serial port discovery function later. 
Are you sure your bafang motor is well connected on your mac and that the serial port you're trying to connect is this one ? 

You can type `ls /dev/ | grep usbserial` to see the usbserial number. 

Tell me if it fixed your issue !

Best,
Clément

**Comment by flochtililoch** [comment]
You were right, my serial port is `/dev/cu.usbserial-1440`. I changed the hard coded value and was able to connect and read my settings. Thanks for providing this code!
